from .sdxl_tensorrt_convert import SDXL_TENSORRT_CONVERTER
from .sdxl_tensorrt_loader import SDXL_TENSORRT_LOADER

NODE_CLASS_MAPPINGS = { 
    "SDXL_TENSORRT_CONVERTER": SDXL_TENSORRT_CONVERTER, 
    "SDXL_TENSORRT_LOADER": SDXL_TENSORRT_LOADER 
}

NODE_DISPLAY_NAME_MAPPINGS = { 
    "SDXL_TENSORRT_CONVERTER": "SDXL TensorRT Converter", 
    "SDXL_TENSORRT_LOADER": "SDXL TensorRT Loader" 
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']