from .unet_tensorrt_convert import UNET_TENSORRT_CONVERTER
from .unet_tensorrt_loader import UNET_TENSORRT_LOADER
from .vae_tensorrt_converter import SDXL_VAE_TENSORRT_CONVERTER
from .vae_tensorrt_loader import SDXL_VAE_TENSORRT_LOADER_DECODER

NODE_CLASS_MAPPINGS = { 
    "UNET_TENSORRT_CONVERTER": UNET_TENSORRT_CONVERTER, 
    "UNET_TENSORRT_LOADER": UNET_TENSORRT_LOADER,
    "VAE_TENSORRT_CONVERTER": SDXL_VAE_TENSORRT_CONVERTER,
    "VAE_TENSORRT_LOADER": SDXL_VAE_TENSORRT_LOADER_DECODER,
}

NODE_DISPLAY_NAME_MAPPINGS = { 
    "UNET_TENSORRT_CONVERTER": "UNET TensorRT Converter", 
    "UNET_TENSORRT_LOADER": "UNET TensorRT Loader",
    "VAE_TENSORRT_CONVERTER": "VAE TensorRT Converter",
    "VAE_TENSORRT_LOADER": "VAE TensorRT Loader (Decoder)",
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']